name: 1. Hello, world!

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
      - name: print, "hello, world!"
        run: echo hello, world!
